#!/usr/bin/env node
/**
 * 企微群推送脚本（增强版）
 * 支持自定义：语言、内容侧重、数量、关键词过滤等
 *
 * ========== 通过环境变量配置 ==========
 * WECHAT_WEBHOOK_URL    - 必填，企微 Webhook 地址
 * PUSH_LANGUAGE         - 语言: zh(中文) | en(英文)，默认 zh
 * PUSH_SECTIONS         - 启用的分类，逗号分隔: x,podcasts,blogs，默认全部
 * MAX_X_TWEETS          - X/Twitter 最大条数，默认 6
 * MAX_PODCASTS          - 播客最大条数，默认 4
 * MAX_BLOGS             - 博客最大条数，默认 4
 * KEYWORDS_INCLUDE      - 只推送包含这些关键词的内容（逗号分隔，可选）
 * KEYWORDS_EXCLUDE      - 排除包含这些关键词的内容（逗号分隔，可选）
 * SHOW_STATS            - 是否显示统计信息: true | false，默认 true
 */

const fs = require('fs');
const path = require('path');

// ========== 配置读取 ==========
const WEBHOOK_URL = process.env.WECHAT_WEBHOOK_URL;
if (!WEBHOOK_URL) {
  console.error('❌ 错误: 未设置 WECHAT_WEBHOOK_URL 环境变量');
  process.exit(1);
}

// 语言配置
const LANG = process.env.PUSH_LANGUAGE || 'zh';
const i18n = {
  zh: {
    title: '🤖 AI Builders 每日摘要',
    datePrefix: '',
    xSection: '📱 X/Twitter 热门动态',
    podcastSection: '🎙️ 播客更新',
    blogSection: '📝 博客精选',
    statsLabel: '📊 今日统计',
    autoGenerated: '> 由 **Follow Builders** 自动生成',
    viewOriginal: '查看原文',
    listen: '收听',
    read: '阅读',
    noContent: '暂无更新',
    unknown: '未知',
  },
  en: {
    title: '🤖 AI Builders Daily Digest',
    datePrefix: '',
    xSection: '📱 X/Trending',
    podcastSection: '🎙️ Podcasts',
    blogSection: '📝 Blog Posts',
    statsLabel: "📊 Today's Stats",
    autoGenerated: '> Auto-generated by **Follow Builders**',
    viewOriginal: 'View Original',
    listen: 'Listen',
    read: 'Read',
    noContent: 'No updates',
    unknown: 'Unknown',
  }
};
const t = i18n[LANG] || i18n.zh;

// 内容配置
const ENABLED_SECTIONS = (process.env.PUSH_SECTIONS || 'x,podcasts,blogs').split(',').map(s => s.trim().toLowerCase());
const MAX_X = parseInt(process.env.MAX_X_TWEETS || '6', 10);
const MAX_PODCASTS = parseInt(process.env.MAX_PODCASTS || '4', 10);
const MAX_BLOGS = parseInt(process.env.MAX_BLOGS || '4', 10);
const KEYWORDS_INCLUDE = process.env.KEYWORDS_INCLUDE ? process.env.KEYWORDS_INCLUDE.split(',').map(k => k.trim().toLowerCase()) : null;
const KEYWORDS_EXCLUDE = process.env.KEYWORDS_EXCLUDE ? process.env.KEYWORDS_EXCLUDE.split(',').map(k => k.trim().toLowerCase()) : [];
const SHOW_STATS = (process.env.SHOW_STATS || 'true').toLowerCase() === 'true';

// ========== 工具函数 ==========
function loadFeed(filename) {
  const filePath = path.join(__dirname, '..', filename);
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf-8'));
  } catch (e) {
    console.warn(`⚠️  无法读取 ${filename}: ${e.message}`);
    return null;
  }
}

/**
 * 关键词过滤
 * @param {string} text - 待过滤文本
 * @returns {boolean} 是否通过过滤
 */
function passesKeywordFilter(text) {
  if (!text) return false;
  const lowerText = text.toLowerCase();

  // 排除过滤
  if (KEYWORDS_EXCLUDE.length > 0 && KEYWORDS_EXCLUDE.some(kw => lowerText.includes(kw))) {
    return false;
  }

  // 包含过滤（如果设置了）
  if (KEYWORDS_INCLUDE && KEYWORDS_INCLUDE.length > 0) {
    return KEYWORDS_INCLUDE.some(kw => lowerText.includes(kw));
  }

  return true;
}

/**
 * 截断文本
 */
function truncate(text, maxLen = 150) {
  if (!text) return '';
  return text.length > maxLen ? text.substring(0, maxLen) + '...' : text;
}

// ========== 格式化各板块 ==========
function formatXSection(feedX) {
  if (!ENABLED_SECTIONS.includes('x')) return '';
  if (!feedX?.x || !Array.isArray(feedX.x) || feedX.x.length === 0) return '';

  let content = `#### ${t.xSection}\n\n`;
  let postCount = 0;

  for (const builder of feedX.x) {
    if (!builder.tweets || !Array.isArray(builder.tweets)) continue;
    if (postCount >= MAX_X) break;

    const author = builder.name || builder.handle || t.unknown;

    for (const tweet of builder.tweets.slice(0, 2)) {
      if (postCount >= MAX_X) break;

      const text = tweet.text || '';
      if (!passesKeywordFilter(text)) continue;

      const tweetUrl = tweet.id ? `https://x.com/${builder.handle}/status/${tweet.id}` : '';
      postCount++;
      content += `${postCount}. **${author}**: ${truncate(text)}\n`;
      if (tweetUrl) content += `   🔗 [${t.viewOriginal}](${tweetUrl})\n`;
    }
  }

  return postCount > 0 ? content + '\n' : '';
}

function formatPodcastSection(feedPodcasts) {
  if (!ENABLED_SECTIONS.includes('podcasts')) return '';
  if (!feedPodcasts?.podcasts || !Array.isArray(feedPodcasts.podcasts) || feedPodcasts.podcasts.length === 0) return '';

  let content = `#### ${t.podcastSection}\n\n`;
  let count = 0;

  for (const podcast of feedPodcasts.podcasts.slice(0, MAX_PODCASTS * 2)) {
    if (count >= MAX_PODCASTS) break;

    const fullText = [podcast.title, podcast.transcript].join(' ');
    if (!passesKeywordFilter(fullText)) continue;

    const title = podcast.title || t.unknown;
    const show = podcast.name || '';
    const summary = truncate((podcast.transcript || '').replace(/\n/g, ' '), 120);
    const url = podcast.url || '';

    count++;
    content += `${count}. **${title}** ${show ? `(${show})` : ''}\n`;
    if (summary) content += `   > ${summary}\n`;
    if (url) content += `   🔗 [${t.listen}](${url})\n`;
  }

  return count > 0 ? content + '\n' : '';
}

function formatBlogSection(feedBlogs) {
  if (!ENABLED_SECTIONS.includes('blogs')) return '';

  let blogsData = null;
  if (feedBlogs) {
    if (Array.isArray(feedBlogs)) blogsData = feedBlogs;
    else if (feedBlogs.blogs?.length) blogsData = feedBlogs.blogs;
    else if (feedBlogs.articles?.length) blogsData = feedBlogs.articles;
  }

  if (!blogsData || blogsData.length === 0) return '';

  let content = `#### ${t.blogSection}\n\n`;
  let count = 0;

  for (const blog of blogsData.slice(0, MAX_BLOGS * 2)) {
    if (count >= MAX_BLOGS) break;

    const fullText = [blog.title, blog.summary, blog.description, blog.excerpt, blog.content].join(' ');
    if (!passesKeywordFilter(fullText)) continue;

    const title = blog.title || t.unknown;
    const source = blog.source || blog.blog || blog.author || '';
    const summary = truncate((blog.summary || blog.description || blog.excerpt || blog.content || '').replace(/\n/g, ' '), 120);
    const url = blog.url || blog.link || '';

    count++;
    content += `${count}. **${title}** ${source ? `(${source})` : ''}\n`;
    if (summary) content += `   > ${summary}\n`;
    if (url) content += `   🔗 [${t.read}](${url})\n`;
  }

  return count > 0 ? content + '\n' : '';
}

function formatStats(feedX, feedPodcasts, blogsData) {
  if (!SHOW_STATS) return '';

  const stats = [];
  let xTweetCount = 0;
  if (feedX?.x) feedX.x.forEach(b => { if (b.tweets) xTweetCount += b.tweets.length; });
  if (xTweetCount) stats.push(`X动态 ${xTweetCount} 条`);
  if (feedPodcasts?.podcasts?.length) stats.push(`播客 ${feedPodcasts.podcasts.length} 期`);
  if (blogsData?.length) stats.push(`博客 ${blogsData.length} 篇`);

  return stats.length > 0 ? `---\n${t.statsLabel}: ${stats.join(' | ')}\n` : '';
}

// ========== 主格式化函数 ==========
function formatDigest() {
  const feedX = loadFeed('feed-x.json');
  const feedPodcasts = loadFeed('feed-podcasts.json');
  const feedBlogs = loadFeed('feed-blogs.json');

  // 获取日期
  const today = new Date().toLocaleDateString(LANG === 'en' ? 'en-US' : 'zh-CN', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    weekday: 'long'
  });

  let content = `### ${t.title}\n`;
  content += `> **${today}**\n\n`;

  // 各板块（按启用顺序输出）
  const sections = [];

  const xContent = formatXSection(feedX);
  if (xContent) sections.push(xContent);

  const podcastContent = formatPodcastSection(feedPodcasts);
  if (podcastContent) sections.push(podcastContent);

  let blogsData = null;
  if (feedBlogs) {
    if (Array.isArray(feedBlogs)) blogsData = feedBlogs;
    else if (feedBlogs.blogs?.length) blogsData = feedBlogs.blogs;
    else if (feedBlogs.articles?.length) blogsData = feedBlogs.articles;
  }

  const blogContent = formatBlogSection(feedBlogs);
  if (blogContent) sections.push(blogContent);

  content += sections.join('\n');

  // 统计信息
  content += formatStats(feedX, feedPodcasts, blogsData);

  content += `\n${t.autoGenerated}`;

  return { content, hasContent: sections.length > 0 };
}

// ========== 推送到企微 ==========
async function pushToWechat(markdownContent) {
  const payload = {
    msgtype: 'markdown',
    markdown: { content: markdownContent }
  };

  console.log('📤 正在推送到企微群...');
  console.log(`--- 消息预览 ---`);
  console.log(markdownContent.substring(0, 800) + '...');
  console.log(`---`);

  try {
    const response = await fetch(WEBHOOK_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload)
    });

    const result = await response.json();

    if (result.errcode === 0) {
      console.log('✅ 推送成功！');
    } else {
      console.error(`❌ 推送失败: ${result.errcode} - ${result.errmsg}`);
      process.exit(1);
    }
  } catch (error) {
    console.error(`❌ 请求失败: ${error.message}`);
    process.exit(1);
  }
}

// ========== 主流程 ==========
async function main() {
  console.log('🚀 开始生成 AI Builders 摘要...\n');
  console.log(`📋 配置: 语言=${LANG}, 板块=${ENABLED_SECTIONS.join(',')}, X上限=${MAX_X}, 播客上限=${MAX_PODCASTS}, 博客上限=${MAX_BLOGS}`);
  if (KEYWORDS_INCLUDE) console.log(`🔍 关键词过滤(包含): ${KEYWORDS_INCLUDE.join(', ')}`);
  if (KEYWORDS_EXCLUDE.length > 0) console.log(`🚫 关键词过滤(排除): ${KEYWORDS_EXCLUDE.join(', ')}`);
  console.log('');

  const { content, hasContent } = formatDigest();

  if (!hasContent) {
    console.warn('⚠️  没有找到可推送的内容，跳过');
    process.exit(0);
  }

  await pushToWechat(content);
}

main();
